/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SequencesIndexRouteImport } from './routes/sequences/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ExercisesIndexRouteImport } from './routes/exercises/index'
import { Route as AuthPathnameRouteImport } from './routes/auth/$pathname'
import { Route as SequencesIdIndexRouteImport } from './routes/sequences/$id/index'
import { Route as ExercisesIdIndexRouteImport } from './routes/exercises/$id/index'
import { Route as SequencesIdEditRouteImport } from './routes/sequences/$id/edit'
import { Route as ExercisesIdEditRouteImport } from './routes/exercises/$id/edit'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SequencesIndexRoute = SequencesIndexRouteImport.update({
  id: '/sequences/',
  path: '/sequences/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesIndexRoute = ExercisesIndexRouteImport.update({
  id: '/exercises/',
  path: '/exercises/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPathnameRoute = AuthPathnameRouteImport.update({
  id: '/auth/$pathname',
  path: '/auth/$pathname',
  getParentRoute: () => rootRouteImport,
} as any)
const SequencesIdIndexRoute = SequencesIdIndexRouteImport.update({
  id: '/sequences/$id/',
  path: '/sequences/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesIdIndexRoute = ExercisesIdIndexRouteImport.update({
  id: '/exercises/$id/',
  path: '/exercises/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const SequencesIdEditRoute = SequencesIdEditRouteImport.update({
  id: '/sequences/$id/edit',
  path: '/sequences/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesIdEditRoute = ExercisesIdEditRouteImport.update({
  id: '/exercises/$id/edit',
  path: '/exercises/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/exercises': typeof ExercisesIndexRoute
  '/login': typeof LoginIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/sequences': typeof SequencesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/exercises/$id/edit': typeof ExercisesIdEditRoute
  '/sequences/$id/edit': typeof SequencesIdEditRoute
  '/exercises/$id': typeof ExercisesIdIndexRoute
  '/sequences/$id': typeof SequencesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/exercises': typeof ExercisesIndexRoute
  '/login': typeof LoginIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/sequences': typeof SequencesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/exercises/$id/edit': typeof ExercisesIdEditRoute
  '/sequences/$id/edit': typeof SequencesIdEditRoute
  '/exercises/$id': typeof ExercisesIdIndexRoute
  '/sequences/$id': typeof SequencesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/exercises/': typeof ExercisesIndexRoute
  '/login/': typeof LoginIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/sequences/': typeof SequencesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/exercises/$id/edit': typeof ExercisesIdEditRoute
  '/sequences/$id/edit': typeof SequencesIdEditRoute
  '/exercises/$id/': typeof ExercisesIdIndexRoute
  '/sequences/$id/': typeof SequencesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/$pathname'
    | '/exercises'
    | '/login'
    | '/onboarding'
    | '/sequences'
    | '/settings'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/exercises/$id/edit'
    | '/sequences/$id/edit'
    | '/exercises/$id'
    | '/sequences/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/$pathname'
    | '/exercises'
    | '/login'
    | '/onboarding'
    | '/sequences'
    | '/settings'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/exercises/$id/edit'
    | '/sequences/$id/edit'
    | '/exercises/$id'
    | '/sequences/$id'
  id:
    | '__root__'
    | '/'
    | '/auth/$pathname'
    | '/exercises/'
    | '/login/'
    | '/onboarding/'
    | '/sequences/'
    | '/settings/'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/exercises/$id/edit'
    | '/sequences/$id/edit'
    | '/exercises/$id/'
    | '/sequences/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthPathnameRoute: typeof AuthPathnameRoute
  ExercisesIndexRoute: typeof ExercisesIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  SequencesIndexRoute: typeof SequencesIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ExercisesIdEditRoute: typeof ExercisesIdEditRoute
  SequencesIdEditRoute: typeof SequencesIdEditRoute
  ExercisesIdIndexRoute: typeof ExercisesIdIndexRoute
  SequencesIdIndexRoute: typeof SequencesIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sequences/': {
      id: '/sequences/'
      path: '/sequences'
      fullPath: '/sequences'
      preLoaderRoute: typeof SequencesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/': {
      id: '/exercises/'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof ExercisesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$pathname': {
      id: '/auth/$pathname'
      path: '/auth/$pathname'
      fullPath: '/auth/$pathname'
      preLoaderRoute: typeof AuthPathnameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sequences/$id/': {
      id: '/sequences/$id/'
      path: '/sequences/$id'
      fullPath: '/sequences/$id'
      preLoaderRoute: typeof SequencesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/$id/': {
      id: '/exercises/$id/'
      path: '/exercises/$id'
      fullPath: '/exercises/$id'
      preLoaderRoute: typeof ExercisesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sequences/$id/edit': {
      id: '/sequences/$id/edit'
      path: '/sequences/$id/edit'
      fullPath: '/sequences/$id/edit'
      preLoaderRoute: typeof SequencesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/$id/edit': {
      id: '/exercises/$id/edit'
      path: '/exercises/$id/edit'
      fullPath: '/exercises/$id/edit'
      preLoaderRoute: typeof ExercisesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthPathnameRoute: AuthPathnameRoute,
  ExercisesIndexRoute: ExercisesIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  SequencesIndexRoute: SequencesIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ExercisesIdEditRoute: ExercisesIdEditRoute,
  SequencesIdEditRoute: SequencesIdEditRoute,
  ExercisesIdIndexRoute: ExercisesIdIndexRoute,
  SequencesIdIndexRoute: SequencesIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
