/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WheelDemoRouteImport } from './routes/wheel-demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SequencesIndexRouteImport } from './routes/sequences/index'
import { Route as PreferencesIndexRouteImport } from './routes/preferences/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as ModifiersIndexRouteImport } from './routes/modifiers/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as HistoryIndexRouteImport } from './routes/history/index'
import { Route as ExercisesIndexRouteImport } from './routes/exercises/index'
import { Route as AchievementsIndexRouteImport } from './routes/achievements/index'
import { Route as AuthPathnameRouteImport } from './routes/auth/$pathname'
import { Route as SequencesIdIndexRouteImport } from './routes/sequences/$id/index'
import { Route as HistoryRecordsIndexRouteImport } from './routes/history/records/index'
import { Route as HistoryCalendarIndexRouteImport } from './routes/history/calendar/index'
import { Route as HistoryIdIndexRouteImport } from './routes/history/$id/index'
import { Route as ExercisesIdIndexRouteImport } from './routes/exercises/$id/index'
import { Route as AccountSettingsIndexRouteImport } from './routes/account/settings/index'
import { Route as SequencesIdExecuteRouteImport } from './routes/sequences/$id/execute'
import { Route as SequencesIdEditRouteImport } from './routes/sequences/$id/edit'
import { Route as ExercisesIdEditRouteImport } from './routes/exercises/$id/edit'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'

const WheelDemoRoute = WheelDemoRouteImport.update({
  id: '/wheel-demo',
  path: '/wheel-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SequencesIndexRoute = SequencesIndexRouteImport.update({
  id: '/sequences/',
  path: '/sequences/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesIndexRoute = PreferencesIndexRouteImport.update({
  id: '/preferences/',
  path: '/preferences/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModifiersIndexRoute = ModifiersIndexRouteImport.update({
  id: '/modifiers/',
  path: '/modifiers/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesIndexRoute = ExercisesIndexRouteImport.update({
  id: '/exercises/',
  path: '/exercises/',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsIndexRoute = AchievementsIndexRouteImport.update({
  id: '/achievements/',
  path: '/achievements/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPathnameRoute = AuthPathnameRouteImport.update({
  id: '/auth/$pathname',
  path: '/auth/$pathname',
  getParentRoute: () => rootRouteImport,
} as any)
const SequencesIdIndexRoute = SequencesIdIndexRouteImport.update({
  id: '/sequences/$id/',
  path: '/sequences/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRecordsIndexRoute = HistoryRecordsIndexRouteImport.update({
  id: '/history/records/',
  path: '/history/records/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryCalendarIndexRoute = HistoryCalendarIndexRouteImport.update({
  id: '/history/calendar/',
  path: '/history/calendar/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIdIndexRoute = HistoryIdIndexRouteImport.update({
  id: '/history/$id/',
  path: '/history/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesIdIndexRoute = ExercisesIdIndexRouteImport.update({
  id: '/exercises/$id/',
  path: '/exercises/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsIndexRoute = AccountSettingsIndexRouteImport.update({
  id: '/account/settings/',
  path: '/account/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SequencesIdExecuteRoute = SequencesIdExecuteRouteImport.update({
  id: '/sequences/$id/execute',
  path: '/sequences/$id/execute',
  getParentRoute: () => rootRouteImport,
} as any)
const SequencesIdEditRoute = SequencesIdEditRouteImport.update({
  id: '/sequences/$id/edit',
  path: '/sequences/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesIdEditRoute = ExercisesIdEditRouteImport.update({
  id: '/exercises/$id/edit',
  path: '/exercises/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/wheel-demo': typeof WheelDemoRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/achievements': typeof AchievementsIndexRoute
  '/exercises': typeof ExercisesIndexRoute
  '/history': typeof HistoryIndexRoute
  '/login': typeof LoginIndexRoute
  '/modifiers': typeof ModifiersIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/preferences': typeof PreferencesIndexRoute
  '/sequences': typeof SequencesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/exercises/$id/edit': typeof ExercisesIdEditRoute
  '/sequences/$id/edit': typeof SequencesIdEditRoute
  '/sequences/$id/execute': typeof SequencesIdExecuteRoute
  '/account/settings': typeof AccountSettingsIndexRoute
  '/exercises/$id': typeof ExercisesIdIndexRoute
  '/history/$id': typeof HistoryIdIndexRoute
  '/history/calendar': typeof HistoryCalendarIndexRoute
  '/history/records': typeof HistoryRecordsIndexRoute
  '/sequences/$id': typeof SequencesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/wheel-demo': typeof WheelDemoRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/achievements': typeof AchievementsIndexRoute
  '/exercises': typeof ExercisesIndexRoute
  '/history': typeof HistoryIndexRoute
  '/login': typeof LoginIndexRoute
  '/modifiers': typeof ModifiersIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/preferences': typeof PreferencesIndexRoute
  '/sequences': typeof SequencesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/exercises/$id/edit': typeof ExercisesIdEditRoute
  '/sequences/$id/edit': typeof SequencesIdEditRoute
  '/sequences/$id/execute': typeof SequencesIdExecuteRoute
  '/account/settings': typeof AccountSettingsIndexRoute
  '/exercises/$id': typeof ExercisesIdIndexRoute
  '/history/$id': typeof HistoryIdIndexRoute
  '/history/calendar': typeof HistoryCalendarIndexRoute
  '/history/records': typeof HistoryRecordsIndexRoute
  '/sequences/$id': typeof SequencesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/wheel-demo': typeof WheelDemoRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/achievements/': typeof AchievementsIndexRoute
  '/exercises/': typeof ExercisesIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/login/': typeof LoginIndexRoute
  '/modifiers/': typeof ModifiersIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/preferences/': typeof PreferencesIndexRoute
  '/sequences/': typeof SequencesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/exercises/$id/edit': typeof ExercisesIdEditRoute
  '/sequences/$id/edit': typeof SequencesIdEditRoute
  '/sequences/$id/execute': typeof SequencesIdExecuteRoute
  '/account/settings/': typeof AccountSettingsIndexRoute
  '/exercises/$id/': typeof ExercisesIdIndexRoute
  '/history/$id/': typeof HistoryIdIndexRoute
  '/history/calendar/': typeof HistoryCalendarIndexRoute
  '/history/records/': typeof HistoryRecordsIndexRoute
  '/sequences/$id/': typeof SequencesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/wheel-demo'
    | '/auth/$pathname'
    | '/achievements'
    | '/exercises'
    | '/history'
    | '/login'
    | '/modifiers'
    | '/onboarding'
    | '/preferences'
    | '/sequences'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/exercises/$id/edit'
    | '/sequences/$id/edit'
    | '/sequences/$id/execute'
    | '/account/settings'
    | '/exercises/$id'
    | '/history/$id'
    | '/history/calendar'
    | '/history/records'
    | '/sequences/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/wheel-demo'
    | '/auth/$pathname'
    | '/achievements'
    | '/exercises'
    | '/history'
    | '/login'
    | '/modifiers'
    | '/onboarding'
    | '/preferences'
    | '/sequences'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/exercises/$id/edit'
    | '/sequences/$id/edit'
    | '/sequences/$id/execute'
    | '/account/settings'
    | '/exercises/$id'
    | '/history/$id'
    | '/history/calendar'
    | '/history/records'
    | '/sequences/$id'
  id:
    | '__root__'
    | '/'
    | '/wheel-demo'
    | '/auth/$pathname'
    | '/achievements/'
    | '/exercises/'
    | '/history/'
    | '/login/'
    | '/modifiers/'
    | '/onboarding/'
    | '/preferences/'
    | '/sequences/'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/exercises/$id/edit'
    | '/sequences/$id/edit'
    | '/sequences/$id/execute'
    | '/account/settings/'
    | '/exercises/$id/'
    | '/history/$id/'
    | '/history/calendar/'
    | '/history/records/'
    | '/sequences/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WheelDemoRoute: typeof WheelDemoRoute
  AuthPathnameRoute: typeof AuthPathnameRoute
  AchievementsIndexRoute: typeof AchievementsIndexRoute
  ExercisesIndexRoute: typeof ExercisesIndexRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ModifiersIndexRoute: typeof ModifiersIndexRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  PreferencesIndexRoute: typeof PreferencesIndexRoute
  SequencesIndexRoute: typeof SequencesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ExercisesIdEditRoute: typeof ExercisesIdEditRoute
  SequencesIdEditRoute: typeof SequencesIdEditRoute
  SequencesIdExecuteRoute: typeof SequencesIdExecuteRoute
  AccountSettingsIndexRoute: typeof AccountSettingsIndexRoute
  ExercisesIdIndexRoute: typeof ExercisesIdIndexRoute
  HistoryIdIndexRoute: typeof HistoryIdIndexRoute
  HistoryCalendarIndexRoute: typeof HistoryCalendarIndexRoute
  HistoryRecordsIndexRoute: typeof HistoryRecordsIndexRoute
  SequencesIdIndexRoute: typeof SequencesIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wheel-demo': {
      id: '/wheel-demo'
      path: '/wheel-demo'
      fullPath: '/wheel-demo'
      preLoaderRoute: typeof WheelDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sequences/': {
      id: '/sequences/'
      path: '/sequences'
      fullPath: '/sequences'
      preLoaderRoute: typeof SequencesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences/': {
      id: '/preferences/'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modifiers/': {
      id: '/modifiers/'
      path: '/modifiers'
      fullPath: '/modifiers'
      preLoaderRoute: typeof ModifiersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/': {
      id: '/exercises/'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof ExercisesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements/': {
      id: '/achievements/'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$pathname': {
      id: '/auth/$pathname'
      path: '/auth/$pathname'
      fullPath: '/auth/$pathname'
      preLoaderRoute: typeof AuthPathnameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sequences/$id/': {
      id: '/sequences/$id/'
      path: '/sequences/$id'
      fullPath: '/sequences/$id'
      preLoaderRoute: typeof SequencesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/records/': {
      id: '/history/records/'
      path: '/history/records'
      fullPath: '/history/records'
      preLoaderRoute: typeof HistoryRecordsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/calendar/': {
      id: '/history/calendar/'
      path: '/history/calendar'
      fullPath: '/history/calendar'
      preLoaderRoute: typeof HistoryCalendarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$id/': {
      id: '/history/$id/'
      path: '/history/$id'
      fullPath: '/history/$id'
      preLoaderRoute: typeof HistoryIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/$id/': {
      id: '/exercises/$id/'
      path: '/exercises/$id'
      fullPath: '/exercises/$id'
      preLoaderRoute: typeof ExercisesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/settings/': {
      id: '/account/settings/'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sequences/$id/execute': {
      id: '/sequences/$id/execute'
      path: '/sequences/$id/execute'
      fullPath: '/sequences/$id/execute'
      preLoaderRoute: typeof SequencesIdExecuteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sequences/$id/edit': {
      id: '/sequences/$id/edit'
      path: '/sequences/$id/edit'
      fullPath: '/sequences/$id/edit'
      preLoaderRoute: typeof SequencesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/$id/edit': {
      id: '/exercises/$id/edit'
      path: '/exercises/$id/edit'
      fullPath: '/exercises/$id/edit'
      preLoaderRoute: typeof ExercisesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WheelDemoRoute: WheelDemoRoute,
  AuthPathnameRoute: AuthPathnameRoute,
  AchievementsIndexRoute: AchievementsIndexRoute,
  ExercisesIndexRoute: ExercisesIndexRoute,
  HistoryIndexRoute: HistoryIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  ModifiersIndexRoute: ModifiersIndexRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  PreferencesIndexRoute: PreferencesIndexRoute,
  SequencesIndexRoute: SequencesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ExercisesIdEditRoute: ExercisesIdEditRoute,
  SequencesIdEditRoute: SequencesIdEditRoute,
  SequencesIdExecuteRoute: SequencesIdExecuteRoute,
  AccountSettingsIndexRoute: AccountSettingsIndexRoute,
  ExercisesIdIndexRoute: ExercisesIdIndexRoute,
  HistoryIdIndexRoute: HistoryIdIndexRoute,
  HistoryCalendarIndexRoute: HistoryCalendarIndexRoute,
  HistoryRecordsIndexRoute: HistoryRecordsIndexRoute,
  SequencesIdIndexRoute: SequencesIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
